import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  // Ignore build output, generated files, and non-browser runtimes.
  // src/components/ui/** are auto-generated by shadcn — treat as vendor.
  // supabase/functions/** run in Deno, not Node/browser — incompatible rules.
  {
    ignores: [
      'dist',
      'build',
      'coverage',
      'src/integrations/supabase/types.ts',
      'src/components/ui/**',
      'supabase/functions/**',
    ],
  },

  // Base + TypeScript recommended
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.es2022 },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,

      // Warn instead of error so dev velocity isn't blocked, but CI sees them.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Turn unused-vars back ON (Lovable had it off).
      // Allow underscore-prefixed args/vars to opt out — useful for unused callback params.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // `any` is a smell — warn but don't block. Phase 1 will eliminate the remaining ones.
      '@typescript-eslint/no-explicit-any': 'warn',

      // Common foot-guns
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-debugger': 'warn',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'smart'],
    },
  },

  // Provider + context files export both a component and hooks from the same
  // file — intentional architectural pattern. React Refresh can still handle
  // it; the rule adds no safety here.
  {
    files: ['**/providers/**/*.{ts,tsx}', '**/context.{ts,tsx}', '**/context/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  // Node-context config files
  {
    files: ['*.config.{js,ts}', 'vite.config.ts', 'vitest.config.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // Off-limits directories carry pre-existing a11y issues that are deferred to
  // a dedicated pass. Suppress only the rules that would otherwise block CI.
  {
    files: [
      'src/pages/admin/**/*.{ts,tsx}',
      'src/pages/office/**/*.{ts,tsx}',
      'src/pages/user/**/*.{ts,tsx}',
      'src/features/**/*.{ts,tsx}',
      'src/routes/**/*.{ts,tsx}',
    ],
    rules: {
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/aria-role': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
    },
  },

  // Disable ESLint stylistic rules that Prettier owns. KEEP THIS LAST.
  prettierConfig,
);
